name: Tests

on: push

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Unit Testing
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: dotnet build
      - run: dotnet test
