name: Tests

on: push

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dotnet-version: ["7.0.201"]
    name: Unit Testing
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Build Solution
        run: dotnet build TestCiCd
      - name: Run test
        run: dotnet test
