name: Tests

on: push

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dotnet-version: ["7.0.0", "7.0.1", "7.0.2", "7.0.3", "7.0.4"]
    name: Unit Testing
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Build Solution
        run: dotnet build
      - name: Run test
        run: dotnet test
